/*
	Warfield - Functions Forwards
	
	Author: KaryM711
	Language: Pawn
*/

forward OnPlayerDataChecked(playerid, corrupt_check);

forward public OnPlayerRegister(playerid);

forward public OnUpdate();

forward BanPlayer(playerid);

forward KickEx(playerid);

forward SendRandomMessage();

forward OnZoneUpdate(zoneid);

forward AirstrikeTimer(playerid);

forward UpdateLaunchTime();

forward AutoSaveTimer();

forward OnPlayerLeaveGame(playerid);